### ISSUE TITLE
Possible to render in Shadow DOM?

### ISSUE THREAD

**Issue by awwester** [effektif/react-mentions#178] opened 2017-08-08 00:42 UTC
There seems to be a problem when using this package in the Shadow DOM and I'm curious if it's possible to use react-mentions when your react app is rendered in the Shadow DOM, or if it's not currently supported.

The problem comes down to the onChange event is not being dispatched for the Mention component, whereas in the normal DOM the onChange event is fired and brings up the supplied data options without problem.

There are issues with events not working as expected with React in the Shadow DOM, however the [react-shadow](https://github.com/Wildhoney/ReactShadow) package takes care of those issues and I've verified that the events are being dispatched correctly for other components and DOM elements - however with react-shadow (and other mention-based packages as well) the onChange event is not seen.

**Comment by frontendphil** [comment] 2017-08-08 11:43
Phew, we've never encountered that. Could you provide us with a code snippet that highlights this?

**Comment by awwester** [comment] 2017-08-08 12:24
Let's take the following simple Mention code here:

```
  constructor(props) {
    super(props);

    this.state = { value: 'asdf' };
  }

  handleChange = e => this.setState({ value: e.target.value });

  render() {
    const users = [
      {
        id: 'walter',
        display: 'Walter White',
      },
      {
        id: 'jesse',
        display: 'Jesse Pinkman',
      }
    ];

    return (
      <MentionsInput value={this.state.value} onChange={this.handleChange}>
        <Mention trigger="@" data={users} />
      </MentionsInput>
    );
  }
```

This code works when I put it into a react app that is rendered into the DOM, meaning that the ReactDOM.render method is used on a node in the DOM

```
ReactDOM.render(
  <Provider store={store}>
    <Router history={browserHistory} routes={Routes} />
  </Provider>,
  document.getElementById('root')
);
```

We have a chrome extension project that needs to use the Shadow DOM instead of the normal DOM. It changes the rendering part to be something like the following.

```
import ShadowDOM from 'react-shadow';

ReactDOM.render(
    <ShadowDOM>
      <div>
        <App  />
      </div>
    </ShadowDOM>,   document.getElementById('root')
);
```

**Comment by carlotapia** [comment] 2017-08-11 15:39
Bump. Experiencing the same issue.

**Comment by frontendphil** [comment] 2017-08-12 11:23
I'll have a look at this next week. Let's see if I can reproduce by adding a Shadow DOM example to our examples page.

**Comment by awwester** [comment] 2017-08-12 12:53
@frontendphil thanks man, much appreciated. Here are a couple things I've found so far:

the onChange event is broken due to this line: https://github.com/effektif/react-mentions/blob/master/src/MentionsInput.js#L238

When react is rendered in the Shadow DOM the events need to be retargeted so that react is aware of the events, which means the event target will not be the active element. Without changing this IE bug fix the onChange event does not get fired.

The suggestions/highlights node can't be found with `ReactDOM.findDOMNode` because they're not in the DOM: https://github.com/effektif/react-mentions/blob/master/src/MentionsInput.js#L406

**Comment by carlotapia** [comment] 2017-08-20 18:32
@frontendphil +1 A Shadow DOM example would be awesome!

**Comment by carlotapia** [comment] 2017-09-04 02:27
Bump :)

**Comment by frontendphil** [comment] 2017-09-12 08:48
I fiddled around with this a little. The current results are in the `improvement/shadow-dom` branch. `react-mentions` now handles the shadow dom correctly. However, it seems `react` itself has some issues with event delegation inside the shadow-dom [1, 2]. This is probably something that `react-mentions` cannot fix. But there seems to be a solution that can be applied in user land [3].

[1] https://stackoverflow.com/questions/37866237/click-event-not-firing-when-react-component-in-a-shadow-dom
[2] https://github.com/facebook/react/issues/10422
[3] https://www.npmjs.com/package/react-shadow-dom-retarget-events

**Comment by awwester** [comment] 2017-09-12 14:19
hmmm this didn't seem to fix the issues for us. The two examples I had given in my Aug 12 comment don't seem to have been changed so the app is still getting stuck in those spots. 

For example this line is still blocking anything in the handleOnChange https://github.com/effektif/react-mentions/blob/improvement/shadow-dom/src/MentionsInput.js#L266

You're right in regards to the react fix - that is a separate issue that won't be handled in react-mentions. The events need to be retargeted separately.

I'm going to take a closer look again and see if I can get it working in our project and maybe the changes could be merged into this repo.

**Comment by frontendphil** [comment] 2017-09-12 15:18
The line you posted should actually be working now. I changed how the current document is retrieved and that incorporates shadow dom. 

I'm currently stuck at the `onSelect` event not being triggered and have created an issue here: https://github.com/WeltN24/react-shadow-dom-retarget-events/issues/3

After that, the `refs` might become a problem, but we're only getting to this once the event handlers are fixed.

**Comment by awwester** [comment] 2017-10-07 15:35
@frontendphil looks like the onSelect event may have been fixed in WeltN24/react-shadow-dom-retarget-events#3. Have you had a chance to bring that into react-mentions and test it out?

**Comment by frontendphil** [comment] 2018-01-09 08:56
Sorry for not getting back to you on this. For now it seems almost impossible to make `react-mentions` work on the shadow dom. At least from our lib standpoint. We would need to add quite a lot of extra handling to support this edge-case scenario. For that reason I'm closing this issue.

**Closed by frontendphil** 2018-01-09 08:56 UTC
Labels: help wanted
