### ISSUE TITLE
Twitter Handles can't be used as "markup" value

### ISSUE THREAD

**Issue by johannesnagl** [effektif/react-mentions#78] opened 2016-01-29 19:48 UTC
Hi guys,

weird problem: I want to do build a textarea with a twitter autocomplete. When a user enters "@" it should start the autocomplete process. for example: `this is a test, hello @jollife`. 

As a result, I want the text to stay the same `this is a test, hello @jollife`. When using `@__id__` as markup value, the whole process gets stuck:

typing the first `@j` would lead to a highlighted `j`, and cursor is captured and i can't add a single more character.

When using `"@@__id__"` and typing `"@jollife"` only the "@" gets highlighted and the underlying value of the form field is `@@@jollife`. 

When using `"__display__"` it kind of works, but the whole text is highlighted. and when I choose a specific twitter handle, I get a second suggestion after adding the first to the textarea.

**Comment by jfschwarz** [comment] 2016-02-01 08:02
I'm afraid using the markup `@__id__` is currently not supported. That is because internally we'd generate the regexp `@(.+?)` for matching mentions in the text value. What you'd need however is a regexp, such as `@(\w+)`. 

It seems a good idea to allow users to optionally specify a custom regex for markup matching.

**Comment by jfschwarz** [comment] 2016-02-24 11:10
This is related to #21

**Comment by jfschwarz** [comment] 2016-02-25 15:17
Actually, this even is a duplicate of #21

**Closed by jfschwarz** 2016-02-25 15:17 UTC
Labels: duplicate

**Comment by jfschwarz** [comment] 2016-02-25 15:23
@johannesnagl If you want to work on a solution for this, take a look at the `custom-regex` branch, where I started implementing customizability for markup matching some time ago, but it's obviously quite outdated.
