### ISSUE TITLE
Backspace deletes everything in IE

### ISSUE THREAD

**Issue by frontendphil** [effektif/react-mentions#13] opened 2015-01-20 12:58 UTC
In IE, when you try to delete something using backspace, then _everything_ before the current cursor position is being deleted. Not cool.

**Comment by frontendphil** [comment] 2015-01-20 12:59
Seen in IE 11, so probably also an issue in any earlier version.

**Comment by jfschwarz** [comment] 2015-03-13 15:53
duplicate of #3

**Closed by jfschwarz** 2015-03-13 15:53 UTC
Labels: bug, duplicate
